name: change-point-synthetic
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.5
  - numpy=2.0
  - pandas=2.3
  - scipy=1.13
  - scikit-learn=1.6
  - tqdm=4.67
  - matplotlib=3.9
  - seaborn=0.13
  - pyyaml=6.0
  - pytest=8.4
  - tensorboard
